---
- name: Get Deployments with "shipping" in their name
  hosts: k8s_nodes
  tasks:
    - name: Get all deployments with "shipping" in their name
      shell: |
        kubectl get deployments --all-namespaces | grep shipping | awk '{print $1 "," $2}'
      register: var_1
    - name: Store deployment details in variables
      set_fact:
        deployment_name: "{{ item.split(',')[1] }}"
        name_space: "{{ item.split(',')[0] }}"
      with_items: "{{ var_1.stdout_lines }}"
    - name: Get deployment details
      shell: |
        kubectl get deployment {{ deployment_name }} -n {{ name_space }} -o json
      register: var_2
    - name: Create secret for deployment
      shell: |
        kubectl create secret generic my-secret --from-literal=username=myuser --from-literal=password=mypass --namespace {{ name_space }}
      register: var_3
      ignore_errors: False
    - name: Display result in json format
      debug:
        var: var_3
