---
- name: K8s deployment update playbook
  hosts: k8s_nodes
  gather_facts: false
  tasks:
    - name: Get deployment list with "web"
      shell: |
        kubectl get deployments --namespace robot-shop | awk '{print $1}' | grep web
      register: var_1

    - name: Store deployment details
      set_fact:
        deployment_name: "{{ var_1.stdout_lines[0] }}"
        name_space: "robot-shop"
      when: "'web' in var_1.stdout"
    - name: Get deployment details
      shell: |
        kubectl get deployment -o json --namespace {{ name_space }} {{ deployment_name }}
      register: var_2

    - name: Restart the pods to solve process crash process for deployment
      shell: |
        kubectl rollout restart deployment {{ deployment_name }} -n {{ name_space }}
      when: "'web' in var_1.stdout"

    - name: Get updated deployment details
      shell: |
        kubectl get deployment -o json --namespace {{ name_space }} {{ deployment_name }}
      register: var_3

    - name: Display updated deployment details
      debug:
        var: var_3.stdout
