---
- name: K8s deployment update playbook
  hosts: k8s_nodes
  gather_facts: false
  tasks:
    - name: Get deployment list with "shipping"
      shell: |
        kubectl get deployments --all-namespaces | awk '{print $1,$2}' | grep shipping
      register: var_1
    - name: Get deployment details
      shell: |
        kubectl get deployment -o json --namespace {{ name_space }} {{ deployment_name }}
      register: var_2
    - name: Get replicasets for the deployment
      shell: |
        kubectl get replicasets -n {{ name_space }} --selector=app={{ deployment_name }}
      register: var_3
    - name: Display result in json format
      debug:
        var: var_2.stdout
