---
- name: K8s deployment update playbook
  hosts: k8s_nodes
  gather_facts: false
  tasks:
    - name: Get deployment details
      shell: |
        kubectl get deployment web -n robot-shop -o json
      register: var_1

    - name: Get network policies
      shell: |
        kubectl get networkpolicies -n robot-shop -o json
      register: var_2

    - name: Display deployment and network policies details
      debug:
        var: var_1.stdout + "\n" + var_2.stdout
