---
- name: K8s deployment update playbook
  hosts: k8s_nodes
  gather_facts: false
  tasks:
    - name: Get deployment list with "temp"
      shell: |
        kubectl get deployments --all-namespaces | awk '{print $1,$2}' | grep "temp"
      register: var_1
    - name: Split deployment name and namespace
      set_fact:
        deployment_name: "{{ var_1.stdout_lines[0].split()[1] }}"
        name_space: "{{ var_1.stdout_lines[0].split()[0] }}"
      when: "'temp' in var_1.stdout"
    - name: Get deployment details
      shell: |
        kubectl get deployment -o json --namespace {{ name_space }} {{ deployment_name }}
      register: var_2
    - name: Solve the process crash that causes incorrect deallocation
      shell: |
        kubectl delete pod -l app={{ deployment_name }} --namespace {{ name_space }}
      when: "'temp' in var_1.stdout"
    - name: Get updated deployment details
      command: |
        kubectl get deployment -o json --namespace {{ name_space }} {{ deployment_name }}
      register: var_3
    - name: Display updated deployment details
      debug:
        var: var_3.stdout

