---
- name: K8s deployment update playbook
  hosts: k8s_nodes
  gather_facts: false
  tasks:
    - name: Get deployment list with "web"
      shell: |
        kubectl get deployments --all-namespaces | awk '{print $1,$2}' | grep web
      register: var_1
    - name: Split deployment name and namespace
      set_fact:
        deployment_name: "{{ var_1.stdout_lines[0].split()[1] }}"
        name_space: "{{ var_1.stdout_lines[0].split()[0] }}"
      when: "'web' in var_1.stdout"
    - name: Get deployment details
      shell: |
        kubectl get deployment -o json --namespace {{ name_space }} {{ deployment_name }}
      register: var_2
      
    - name: Get replicaset name
      shell: |
        kubectl get replicasets --namespace {{ name_space }} | grep {{ deployment_name }} | awk '{print $1}'
      register: replicaset_name
    - name: Display and describe the detailed state of one or more replicasets
      shell: |
        kubectl describe replicasets {{ replicaset_name.stdout }} -n {{name_space}}
      register: var_2
    - name: Display result in json format
      debug: 
        var: var_2
