---
- name: K8s deployment update playbook
  hosts: k8s_nodes
  gather_facts: false
  vars:
    deployment_name: web
    name_space: robot-shop
    retries: 5
    delay: 10
  tasks:
    - name: Check if deployment is available
      shell: |
        kubectl get deployment {{ deployment_name }} -n {{ name_space }} -o json
      register: var_1
      until: var_1 is succeeded
      retries: "{{ retries }}"
      delay: "{{ delay }}"

    - name: Display deployment details
      debug:
        var: var_1.stdout
      when: var_1 is succeeded
      
    - name: Implement retry logic for handling temporary connection failures
      block:
        - name: Try to get deployment details
          shell: |
            kubectl get deployment {{ deployment_name }} -n {{ name_space }} -o json
          register: var_2
          until: var_2 is succeeded
          retries: "{{ retries }}"
          delay: "{{ delay }}"
      rescue:
        - name: Handle failure
          debug:
            msg: "Failed to get deployment details after {{ retries }} attempts. Please check your connection."
When: var_1 is failed
