---
- name: K8s deployment expose playbook
  hosts: k8s_nodes
  gather_facts: false
  tasks:
    - name: Get deployment list with "web"
      shell: |
        kubectl get deployments --all-namespaces | awk '{print $1,$2}' | grep web
      register: var_1
    - name: Split deployment name and namespace
      set_fact:
        deployment_name: "{{ var_1.stdout_lines[0].split()[1] }}"
        name_space: "{{ var_1.stdout_lines[0].split()[0] }}"
      when: "'web' in var_1.stdout"
    - name: Run kubectl to expose a deployment as a new kubernetes service
      shell: |
        kubectl expose deployment/{{ deployment_name }} --type="NodePort" --port=80 --namespace {{ name_space }}
      register: var_2
      when: "'web' in var_1.stdout"
      
    - name: Display updated deployment details
      debug:
        var: var_2.stdout
