---
- name: Node unschedulable
  hosts: k8s_nodes
  gather_facts: false
  tasks:
    - name: Get deployment list with "web"
      shell: |
        kubectl get deployments --all-namespaces | awk '{print $1,$2}' | grep web
      register: var_1
    - name: Split deployment name and namespace
      set_fact:
        deployment_name: "{{ var_1.stdout_lines[0].split()[1] }}"
        name_space: "{{ var_1.stdout_lines[0].split()[0] }}"
      when: "'web' in var_1.stdout"
    - name: Get deployment details
      shell: |
        kubectl get deployment -o json --namespace {{ name_space }} {{ deployment_name }}
      register: var_2
    - name: Schedule deployments on only one node
      shell: |
        kubectl patch deployment {{ deployment_name }} --namespace {{ name_space }} --type='json' -p='[{"op": "add", "path": "/spec/template/spec/nodeSelector", "value":{"node-role.kubernetes.io/master":""}}]'
    - name: Mark node as unschedulable
      shell: |
        kubectl cordon k8s-master1
    - name: Display deployment details
      debug:
        var: var_2
