---
- name: K8s deployment update playbook
  hosts: k8s_nodes
  gather_facts: false
  tasks:
    - name: Get deployment list with "web"
      shell: |
        kubectl get deployments --all-namespaces | awk '{print $1,$2}' | grep web
      register: var_1

    - name: Split deployment name and namespace
      set_fact:
        deployment_name: "{{ var_1.stdout_lines[0].split()[1] }}"
        name_space: "{{ var_1.stdout_lines[0].split()[0] }}"
      when: "'web' in var_1.stdout"

    - name: Get deployment details
      shell: |
        kubectl get deployment -o json --namespace {{ name_space }} {{ deployment_name }}
      register: var_2

    - name: Get memory usage
      shell: |
        kubectl top pod $(kubectl get pods --namespace {{ name_space }} -l app=web -o jsonpath="{.items[0].metadata.name}") --namespace {{ name_space }} | awk 'NR==2{print $3}'
      register: memory_usage

    - name: Decrease replica if memory is high
      shell: |
        kubectl scale --replicas=$[ $(kubectl get deployment {{ deployment_name }} --namespace {{ name_space }} -o jsonpath={.spec.replicas}) - 1 ] deployment/{{ deployment_name }} --namespace {{ name_space }}
      when: memory_usage.stdout|int > 500

    - name: Get updated deployment details
      command: |
        kubectl get deployment -o json --namespace {{ name_space }} {{ deployment_name }}
      register: var_3

    - name: Display updated deployment details in JSON format
      debug:
        var: var_3.stdout
