---
- name: Get Deployments with "shipping" in their name
  hosts: k8s_nodes
  tasks:
    - name: Get all deployments with "shipping" in their name
      shell: |
        kubectl get deployments --all-namespaces | grep shipping | awk '{print $1 "," $2}'
      register: var_1
    - name: Store deployment details in variables
      set_fact:
        deployment_name: "{{ item.split(',')[1] }}"
        name_space: "{{ item.split(',')[0] }}"
      with_items: "{{ var_1.stdout_lines }}"
    - name: Get state full set
      shell: |
        kubectl get statefulset -n {{ name_space}}
      register: var_3
    - name: Display result in json format
      debug:
        var: var_3
