---
- name: K8s deployment update playbook
  hosts: k8s_nodes
  gather_facts: false
  tasks:
    - name: Get deployment list with "shipping"
      shell: |
        kubectl get deployments --all-namespaces | awk '{print $1,$2}' | grep shipping
      register: var_1
    - name: Get deployment details
      shell: |
        kubectl get deployment -o json --namespace {{ name_space }} {{ deployment_name }}
      register: var_2
    - name: Delete statefulset 
      shell: |
        kubectl delete statefulset {{ deployment_name }} --namespace {{ name_space }}
      when: "'shipping' in var_1.stdout"
    - name: Get updated deployment details
      command: |
        kubectl get deployment -o json --namespace {{ name_space }} {{ deployment_name }}
      register: var_3
    - name: Display updated deployment details
      debug:
        var: var_3.stdout
